export const RECORD_PRACTICE_DATA = 'RECORD_PRACTICE_DATA';
export type  RECORD_PRACTICE_DATA = typeof RECORD_PRACTICE_DATA;

export const SAVE_PRACTICE_DATA = 'SAVE_PRACTICE_DATA';
export type  SAVE_PRACTICE_DATA = typeof SAVE_PRACTICE_DATA;